"""RF gun simulation helpers."""

from .config import rft, show_versions, resolve_threads, set_thread_environment
from .constants import c, q_e, ME_MEV
from .helpers import (
	sample_disk,
	min_step,
	med_step,
	fmt_bytes,
)
from .rf_params import (
	delivered_power_on_resonance,
	effective_length_from_abs_ez,
	veff_from_phase_scan_pz,
	r_over_q_per_m,
)
from .field_io import load_fieldmap_mat, interp_cfield, mesh_edge_length_stats
from .phasor import (
	select_iq_snapshots,
	build_iq_phasor,
	build_crest_phasor,
	phasor_check,
)
from .rftrack_volume import (
	VolumeBuildParams,
	ScreenBuildParams,
	build_volume,
	track_volume_with_screens,
	find_Ez_axis_phasor_at_z0,
)
from .simulation import (
	RoughnessParams,
	EmissionParams,
	TrackingParams,
	DiagnosticsParams,
	SimulationResult,
	EXTENDED_PHASE_FMT,
	screen_progress_callback,
	build_bunch_simple,
	build_bunch_thermionic,
	run_phase_scan,
	run_transport_with_progress,
)
from .diagnostics import (
	twiss_from_moments,
	dispersion_from_moments,
	manual_twiss_and_emittance,
	info_get,
	info_get_first,
	snapshot_stats,
	summarize_array,
	build_screen_summary_from_phase_space,
	classify_particle_outcomes,
)
from .io import (
	save_screen_distributions_json,
	save_screen_distributions_hdf5,
	save_lost_particles_json,
	save_beam_openpmd,
	save_run_summary,
	to_json_safe,
)
from .aperture import ApertureParams, aperture_survival_mask, aperture_summary
from .particle_tags import ParticleTags, build_particle_tags, backward_ids_from_bout, tag_mask, surviving_mask
from .beam_properties import compute_beam_properties, transmission_curves
from .back_bombardment import BackBombardmentData, compute_back_bombardment, kinetic_energy_joules, screen_trajectory
from .acceptance_scan import AcceptanceScanResult, scan_acceptance
from .deflection_field import (
	DEFAULT_B_PK_PER_A_T,
	DEFAULT_W_MM,
	DEFAULT_Z_P_MM,
	DeflectionField,
	b0_deflection_T,
)
from .plotting import (
	field_maps,
	axis_phase,
	plot_emission_history,
	plot_j_vs_n,
	plot_phase_space,
	plot_spectra,
	plot_screen_phase_space_slider,
	plot_beam_moments_evolution,
	plot_beam_twiss_evolution,
	phase_plot,
	plot_back_bombardment_phase_space,
	plot_back_bombardment_screen_reach,
	plot_back_bombardment_energy_density,
	plot_back_bombardment_power_density_vs_time,
	plot_acceptance_scan,
	save_run_figures,
	plot_class_conditioned_histograms,
	save_beam_phase_space_json,
	save_screen_phase_space_batch,
	capture_figures,
	FigureCapture,
	PlotStyleConfig,
	DEFAULT_PLOT_STYLE,
	get_default_density_cmap,
	get_aperture_loss_cmap,
	get_recentered_diverging_cmap,
	add_reference_lines,
	COLOR_PRIMARY,
	COLOR_SECONDARY,
	COLOR_NEUTRAL,
)

__all__ = [
	"rft",
	"show_versions",
	"resolve_threads",
	"set_thread_environment",
	"c",
	"q_e",
	"ME_MEV",
	"sample_disk",
	"min_step",
	"med_step",
	"fmt_bytes",
	"delivered_power_on_resonance",
	"effective_length_from_abs_ez",
	"veff_from_phase_scan_pz",
	"r_over_q_per_m",
	"load_fieldmap_mat",
	"interp_cfield",
	"mesh_edge_length_stats",
	"select_iq_snapshots",
	"build_iq_phasor",
	"build_crest_phasor",
	"phasor_check",
	"VolumeBuildParams",
	"ScreenBuildParams",
	"build_volume",
	"track_volume_with_screens",
	"find_Ez_axis_phasor_at_z0",
	"RoughnessParams",
	"EmissionParams",
	"TrackingParams",
	"DiagnosticsParams",
	"SimulationResult",
	"EXTENDED_PHASE_FMT",
	"screen_progress_callback",
	"build_bunch_simple",
	"build_bunch_thermionic",
	"run_phase_scan",
	"run_transport_with_progress",
	"twiss_from_moments",
	"dispersion_from_moments",
	"manual_twiss_and_emittance",
	"info_get",
	"info_get_first",
	"snapshot_stats",
	"summarize_array",
	"build_screen_summary_from_phase_space",
	"classify_particle_outcomes",
	"save_screen_distributions_json",
	"save_screen_distributions_hdf5",
	"save_lost_particles_json",
	"save_run_summary",
	"save_beam_openpmd",
	"to_json_safe",
	"ApertureParams",
	"aperture_survival_mask",
	"aperture_summary",
	"ParticleTags",
	"build_particle_tags",
	"backward_ids_from_bout",
	"tag_mask",
	"surviving_mask",
	"compute_beam_properties",
	"transmission_curves",
	"BackBombardmentData",
	"compute_back_bombardment",
	"kinetic_energy_joules",
	"screen_trajectory",
	"AcceptanceScanResult",
	"scan_acceptance",
	"DEFAULT_B_PK_PER_A_T",
	"DEFAULT_W_MM",
	"DEFAULT_Z_P_MM",
	"DeflectionField",
	"b0_deflection_T",
	"field_maps",
	"axis_phase",
	"plot_emission_history",
	"plot_j_vs_n",
	"plot_phase_space",
	"plot_spectra",
	"plot_screen_phase_space_slider",
	"plot_beam_moments_evolution",
	"plot_beam_twiss_evolution",
	"phase_plot",
	"plot_back_bombardment_phase_space",
	"plot_back_bombardment_screen_reach",
	"plot_back_bombardment_energy_density",
	"plot_back_bombardment_power_density_vs_time",
	"plot_acceptance_scan",
	"save_run_figures",
	"plot_class_conditioned_histograms",
	"save_beam_phase_space_json",
	"save_screen_phase_space_batch",
	"capture_figures",
	"FigureCapture",
	"PlotStyleConfig",
	"DEFAULT_PLOT_STYLE",
	"get_default_density_cmap",
	"get_aperture_loss_cmap",
	"get_recentered_diverging_cmap",
	"add_reference_lines",
	"COLOR_PRIMARY",
	"COLOR_SECONDARY",
	"COLOR_NEUTRAL",
]

from . import finesse_presets
from .finesse_presets import FINESSE_PRESETS, FINESSE_TIERS, finesse_preset_dict, apply_finesse_preset_to_args

__all__ += [
	"finesse_presets",
	"FINESSE_PRESETS",
	"FINESSE_TIERS",
	"finesse_preset_dict",
	"apply_finesse_preset_to_args",
]
